# Analise de Decisao (Condicionais)

Condicionais controlam o fluxo do seu programa baseado nas condições que voce define. Isso permite que seu codigo reponda de alguma forma dependendo dessas condicoes. Voce pode definir qualquer conjunto de condicoes e escrever um codigo que responda exatamente o que voce precisa.

## Sobre declarações condicionais

- O que é uma declaração condicional?

Uma declaracao condicional checa alguma condicao verdadeira antes de executar o codigo.


```python

if ingresso_do_cinema > 100:
    print('Está muito caro!')
```

Toda declaracao condicional tem um teste logico que avalia se certa condicao é ```True``` ou ```False```. 


- O que é um valor booleano?


É um valor que pode ser ```True``` ou ```False```.


- Que tipo de teste lógico voce pode performar em uma declaração condicional??

Abaixo temos os testes lógicos que voce pode performar em seu código:

```python

# idade é uma variavel do tipo int

idade == 33 # igualdade

idade != 33 # diferença

idade < 33 # menor que

idade > 33 # maior que

idade <= # menor igual

idade >= # maior igual

# para listas podemos usar as condicionais

'SP' in estados # está na lista, caso verdadeiro, retorna True

'NY' not in estado # não está na lista, caso verdadeiro, retorna False

# any retorna True quando pelo menos 1 elemento é verdadeiro. 

any([True, False])

# all retorna True quando todos os elementos sao verdadeiros.

all([True, False])

```


## Usando IF

- Como voce escreve uma declaração ```if```?

Começamos com ```if``` depois colocamos um teste logico, ou uma variavel booleana seguido de ```:```.

In [1]:
var_bool = True

if var_bool:
    print('Printou pois era verdade!')

Printou pois era verdade!


In [2]:
if not var_bool:
    print('Printou pois era verdade!')

In [3]:
var_bool = False

if var_bool:
    print('Printou pois era falsidade!')

In [4]:
if not var_bool:
    print('Printou pois era falsidade!')

Printou pois era falsidade!


In [5]:
altura = 1.90
if altura > 1.85:
    print('Uma pessoa alta')

Uma pessoa alta


## Usando IF-ELSE

- Como voce escreve uma declaracao ```if-else```?

Em uma declaração ```if-else``` caso o ```if``` seja `False` o código toma o sentido do ```else```.



In [6]:
altura = 1.70
if altura > 1.85:
    print('Uma pessoa alta.')
else:
    print('Vc nao é uma pessoa tão alta.')

Vc nao é uma pessoa tão alta.


- Como voce escreve uma serie de ```if-elif-else```?

Os testes acontecem até que o ```else``` que roda o ultimo código. 


In [9]:
imc = 10
if imc < 5:
    print('Voce precisa comer mais!')
elif imc < 10:
    print('Voce ta bem na fita!')
else:
    print('Amigao, vc precisa de um regime!')

Amigao, vc precisa de um regime!


Os blocos ```if-elif``` não requerem um ```else```

In [10]:
altura = 1.70
if altura > 1.85:
    print('Uma pessoa alta.')
elif altura > 1.75:
    print('Vc nao é uma pessoa tão alta.')

## Input do usuário

- Como voce pede para o usuario inputar um valor?

A funcao ```input()``` pausa o programa e aguarda o usuario entrar com um dado.


In [11]:
nome = input('Digite seu nome: ')
print(f'Olá {nome}!')

Digite seu nome: caio
Olá caio!


- Como voce manipula o dado que o usuario digitou?

Todo dado recebido pela funcao ```input()``` é convertido em uma **string**. Dados numerericos devem ser convertidos para o tipo apropriado antes de vc manipula-los.

In [8]:
preco = int(input('Quer pagar quanto?'))
# completar
if preco > 5000:
    print('Pode levar')
else:
    print('Melhora esse preço chefia')

Quer pagar quanto?800
Melhora esse preço chefia


# Operadores Ternarios

```condicao_se_verdadeira if condicao else condicao_se_falsa```


In [3]:
eh_verdadeiro = True
state = "legal" if eh_verdadeiro else "nao_legal"

In [4]:
state

'legal'

In [6]:
dinheiro = 1000
preco = 800

## Usando Tuplas

In [8]:
('nao_comprar', 'comprar')[dinheiro > preco]

'comprar'

## Usando or

In [9]:
True or 'Alguma coisa'

True

In [10]:
False or 'Alguma coisa'

'Alguma coisa'

In [13]:
not (dinheiro > preco) or 'Comprar'

'Comprar'

In [15]:
(dinheiro < preco) or 'Nao_Comprar'

'Nao_Comprar'

# Operador bitwise

In [2]:
chave = 'abc'

In [3]:
frase = 'oioioioi'

In [6]:
chave.encode('ascii') and frase.encode('ascii')

b'oioioioi'

In [19]:
import struct

In [54]:
x = chave
x = '\x00' * (4-len(x)) + x
number = struct.unpack('!i', x.encode())[0]

In [56]:
x = chave
x = '\x00' * (4-len(x)) + x
number2 = struct.unpack('!i', x.encode())[0]

In [86]:
import numpy as np

In [81]:
a = [0,1,0,1]
a = np.array(a)

In [82]:
b = [1,0,1,0]
b = np.array(b)

In [83]:
a | b

array([1, 1, 1, 1])

In [84]:
a & b

array([0, 0, 0, 0])

In [90]:
a << 4

array([ 0, 16,  0, 16])

In [100]:
1 << 2

4

In [1]:
def potencia_2(exp):
    return 1 << exp

In [2]:
%%timeit
potencia_2(1600)

361 ns ± 21.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [3]:
%%timeit
2**1600

2.99 µs ± 289 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [121]:
%%timeit
np.power(2,1600)

3.28 µs ± 260 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [122]:
potencia_2(1600) == 2**1600

True

In [123]:
np.power(2,1600) == 2**1600

False

In [18]:
True | False

True

In [24]:
8 << 1

16

In [16]:
3 & 2

2

In [17]:
1 | 2

3

## While Loops

- O que é um ```while``` loop?

O ```while loop``` roda o codigo enquanto a condicao é verdadeira (```True```). 

In [17]:
contagem = 10
while contagem > 0:
    print(f'{contagem}')
    contagem -= 1
print('Houston o foguete está decolando!')

10
9
8
7
6
5
4
3
2
1
Houston o foguete está decolando!


- Como voce usa uma lista com um ```while``` loop?

In [ ]:
bugs = ['bug_1', 'bug_2', 'bug_3']
while bugs:
    bug = bugs.pop()
    print(f'Arrumando o {bug}')
print('Todos os bugs foram arrumados!')

## Usando Break e Continue

- O que o ```break``` faz com o loop?

O ```break``` finaliza o loop quando certa condição ocorre.



In [18]:
while True:
    nome = input('Qual é o seu nome: ')
    if nome == 'sair':
        break
    print(f'Olá {nome}')

Qual é o seu nome: caio
Olá caio
Qual é o seu nome: gil
Olá gil
Qual é o seu nome: igor
Olá igor
Qual é o seu nome: sair



- O que o ```continue``` faz com o loop?

A palavra chave ```continue``` quebra a sequencia abaixo de loop e retorna para o inicio do loop.

In [5]:
any([True, True])

True

In [6]:
all([True, True])

True

In [1]:
any([True, False])

True

In [2]:
all([True, False])

False

In [3]:
any([False, False])

False

In [4]:
all([False, False])

False

In [1]:
count = 0

SyntaxError: invalid syntax (<ipython-input-2-b905449f8532>, line 1)

In [3]:
count++

SyntaxError: invalid syntax (<ipython-input-3-53d1c51abd20>, line 1)

In [4]:
count+=1